services:
  ############
  # DATABASE #
  ############

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skala_ap2
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #########
  # UTILS #
  #########

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_LOGS: '-error'

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
      MINIO_DEFAULT_BUCKET: greencomplai
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        echo '### MinIO setup started' &&
        mc alias set local http://minio:9000 root rootpassword &&
        if mc ls local/greencompai 2>/dev/null; then
          echo 'Bucket greencomplai already exists';
        else
          mc mb local/greencomplai
          mc anonymous set download local/greencomplai
          echo 'Bucket greencomplai created and set to public access';
        fi &&
        echo '### MinIO setup ended'
      "
networks:
  default:
    name: ap2-dev
    driver: bridge

volumes:
  postgres-data:
