frontend:run-tests:
  needs: []
  stage: test
  extends: .default
  script:
    - npx nx run frontend:test
  artifacts:
    paths:
      - ./apps/frontend/coverage
    expire_in: 1 week
  only:
    - merge_requests
    - main

frontend:sonarqube-check-mr:
  needs:
    - frontend:run-tests
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/apps/frontend/.sonar' # Defines the location of the analysis task cache
    SONAR_PROJECT_BASE_DIR: '${CI_PROJECT_DIR}/apps/frontend' # Defines the location of the project
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - ${CI_PROJECT_DIR}/apps/frontend/.sonar
  script:
    - >
      sonar-scanner
      -Dsonar.projectBaseDir=${SONAR_PROJECT_BASE_DIR}
      -Dsonar.pullrequest.key=${CI_MERGE_REQUEST_IID}
      -Dsonar.pullrequest.branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
      -Dsonar.pullrequest.base=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests

frontend:sonarqube-check-main:
  needs:
    - frontend:run-tests
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/apps/frontend/.sonar' # Defines the location of the analysis task cache
    SONAR_PROJECT_BASE_DIR: '${CI_PROJECT_DIR}/apps/frontend' # Defines the location of the project
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - ${CI_PROJECT_DIR}/apps/frontend/.sonar
  script:
    - >
      sonar-scanner
      -Dsonar.projectBaseDir=${SONAR_PROJECT_BASE_DIR}
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main

frontend:build:
  stage: build
  extends: .default
  script:
    - npx nx run frontend:build --verbose
  artifacts:
    paths:
      - dist/apps/frontend
  only:
    - merge_requests
    - tags
    - main

frontend:archive:
  needs:
    - frontend:build
  stage: archive
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull --cache-from ${CRI_PATH}/frontend --build-arg APP=frontend -t ${CRI_PATH}/frontend:$CI_COMMIT_TAG -f docker/angular.dockerfile  .
    - docker push ${CRI_PATH}/frontend:$CI_COMMIT_TAG
  only:
    - tags
