name: Deploy

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  # Just for testing
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images for nx Apps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci && npx prisma generate --generator jsclient

      - name: Build all nx apps
        run: npx nx run-many --target=build --all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images for all apps
        run: |
          APPS=$(npx nx show projects --type=app)
          TAG=${GITHUB_REF#refs/tags/}
          for APP in $APPS; do
            IMAGE="ghcr.io/${{ github.actor }}/$APP:$TAG"
            docker build -t $IMAGE -f apps/$APP/Dockerfile .
            docker push $IMAGE
          done
